# Generated by Django 5.2.1 on 2025-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='s3_image_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='face_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
