# Generated by Django 5.2.1 on 2025-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointmentslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
